version: "3"

services:
  pican:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/app:delegated
    hostname: pican
    network_mode: host
    # networks:
    #   - pican-network
    cap_add:
      - NET_ADMIN
    privileged: true

# networks:
#   pican-network:
#     name: pican-network
